whitespace = _{ " " | "\t" }

ipv4_chunk = { ('1'..'2') ~ ASCII_DIGIT{2} | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT | ASCII_DIGIT }
ipv4 = { ipv4_chunk ~ "." ~ ipv4_chunk ~ "." ~ ipv4_chunk ~ "." ~ ipv4_chunk }
ip = @{ ipv4 }

hostname = @{ (ASCII_ALPHANUMERIC | "-" | ".")+ }
hostnames = { (whitespace+ ~ hostname)* ~ whitespace* }

comment = _{ "#" ~ (!"\n" ~ ANY)* }
statement = { ip ~ hostnames }
main = _{ SOI ~ "\n"* ~ (statement? ~ comment? ~ "\n"+)* ~ statement? ~ EOI }